### ISSUE TITLE
Notify Package maintainers of Split

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Sane#1]
Debian and Redhat currently package their sane packages from the Pillow source package. It would be good to notify them before the code drops for a new release.

**Comment by manisandro** [comment]
Hi, I'm the Fedora Pillow maintainer. Could you please tag a release, so that I know what version to use for the new python-sane package? Perhaps just call it 2.7.0 for continuity?

**Comment by manisandro** [comment]
Oh, and please add a license file.

**Comment by wiredfool** [comment]
Thanks for the PR. I agree with the 2.7 release number, given that Debian has also been incrementing the sane version along with Pillow.

**Comment by wiredfool** [comment]
Tagged, updated changes and readme a bit with the new versions and maintainer status.

**Comment by manisandro** [comment]
Ok, thanks! By the way, having worked a bit with SANE, I can maintain this if desired. Not expecting much to happen, but if a bug report comes in, I can look at fixing it.

**Comment by wiredfool** [comment]
@manisandro You should be invited to admin this repo. Use your newfound powers (such as they are) for good. 

@aclark4life

**Comment by manisandro** [comment]
Ok, thanks! I suppose this ticket here can be closed, Debian having been notified and Fedora being the upstream of the other Redhat distros, they'll get the changes next time they sync with Fedora.

**Comment by wiredfool** [comment]
OK, let me know if you need anything.

**Comment by manisandro** [comment]
Ok! The note about non-active maintenance can be removed I suppose?

**Comment by wiredfool** [comment]
Yep, now that it's done its job and attracted a maintainer.

**Comment by manisandro** [comment]
Right :) Done.
