### ISSUE TITLE
Unable to locate libsane-dev on Travis CI

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Sane#19]
Travis has started failing Sane builds - https://travis-ci.org/python-pillow/Sane/jobs/100606154 - with the error message -

    E: Unable to locate package libsane-dev

    The command "sudo apt-get install libsane-dev" failed and exited with 100 during .

I found https://github.com/travis-ci/travis-ci/issues/3994 where a request was submitted to whitelist the the package. Would this just be a case of the package disappearing off the whitelist, and a new request needing to be submitted?

**Comment by hugovk** [comment]
travis-ci/travis-ci#3994 is to add libsane-dev to a whitelist so it can be used in container-based builds, which don't allow sudo.

So #20 fixes this to use container-based builds, which also means builds start up quicker.

**Comment by radarhere** [comment]
Nice, thanks for creating that solution.
