### ISSUE TITLE
Are the elements of tupels of sane.get_devices correct "described"?

### ISSUE THREAD

**Issue by TKaluza** [python-pillow/Sane#25]
Hi there!

First of all, thanks for doing this, it's really great!

By using `sane.get_devices()` I get the device_name [OK], vendor [OK], Friendly-Name [instead of model?], machine type (exact model name) [OK].

As being not very good at the english language I maybe have the wrong idea about the use of the word *model* in this context. 

Or should this element 'model' usually contain the exact scanner type/model?
(I'm using a brother network scanner device. Model: MFC-J6520DW)

Thank you :smile_cat:

**Comment by manisandro** [comment]
Typically `vendor` + `model` form the string you'd use to describe the scanner in i.e. a selection menu. It is however up to the scanner driver how it populates these fields. But `MFC-J6520DW` seems to me a fair value for `model`, so I'm not sure I understood your point correctly?

**Comment by manisandro** [comment]
Closing since no reply, feel free to reopen if concerns remain.
