### ISSUE TITLE
Problem with example.py

### ISSUE THREAD

**Issue by israelbejarano** [python-pillow/Sane#36]
Hello:

I am trying to run the example.py file and I get the following error:
Available devices: []
Traceback (most recent call last):
file "example.py", line 29, in <module>
dev = sane.open (devices [0] [0])
IndexError: list index out of range.
I understand that it is because it does not recognize any scanner / printer.

It's a network scanner and my operating system is recognizing it.

Regards.

**Comment by manisandro** [comment]
This is unlikely a python-sane specific issue but rather that sane in general does not pick up the scanner. Does `scanimage -L` report any scanners?

**Comment by manisandro** [comment]
Closing, feel free to reopen if still an issue.
