### ISSUE TITLE
'Document feeder out of documents' was raised by self.device.snap(True).

### ISSUE THREAD

**Issue by LightTemplar** [python-pillow/Sane#53]
class _SaneIterator, method next(self):
the Exception 'Document feeder out of documents' was raised by self.device.snap(True). Could you put it also inside "try ... except" block?

**Comment by manisandro** [comment]
Please test https://github.com/python-pillow/Sane/commit/4a5a549771781b1cd126cf36391336a454c3cf2b

**Comment by LightTemplar** [comment]
It works!
