### ISSUE TITLE
Not able to install sane

### ISSUE THREAD

**Issue by swamyaddala** [python-pillow/Sane#55]
error:  
running build
running build_py
running build_ext
building '_sane' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c _sane.c -o build/temp.linux-x86_64-3.7/_sane.o
_sane.c:30:10: fatal error: sane/sane.h: No such file or directory
 #include <sane/sane.h>
          ^~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by manisandro** [comment]
You need to install the sane-devel package or similar.

**Comment by eliasheuninck** [comment]
Installing the libsane-dev package includes the /sane/sane.h file.
$ sudo apt install libsane-dev
I was able to run python-sane after this.

Got the info from hugovk here: https://github.com/python-pillow/Sane/issues/10

**Comment by k-zet** [comment]
> Installing the libsane-dev package includes the /sane/sane.h file. $ sudo apt install libsane-dev I was able to run python-sane after this.
> 
> Got the info from hugovk here: #10

thank you!
