### ISSUE TITLE
class _SaneIterator next method only for Python 2.7

### ISSUE THREAD

**Issue by dkellygb** [python-pillow/Sane#67]
I installed python3-sane from the Debian/Ubuntu repositories.  It installed version (2.8.3-4build1).  In sane.py, the class _SaneIterator has a `def next(self):` method.  For Python 3 it should be `def __next__(self):`

**Comment by manisandro** [comment]
Thanks for reporting the issue, can you submit a PR with the fix?

**Comment by radarhere** [comment]
This was actually already done in #59. I guess the problem is that there hasn't been a release since then.

**Comment by manisandro** [comment]
Fair point, I've tagged v2.9.0 now.
