### ISSUE TITLE
Missing include sane.h when building sane on Windows

### ISSUE THREAD

**Issue by erberj** [python-pillow/Sane#80]
When I follow your description I get the following error:

PS D:\devel\python-sane-2.9.1\python-sane-2.9.1> python setup.py build
running build
running build_py
creating build
creating build\lib.win-amd64-cpython-310
copying sane.py -> build\lib.win-amd64-cpython-310
running build_ext
building '_sane' extension
creating build\temp.win-amd64-cpython-310
creating build\temp.win-amd64-cpython-310\Release
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tc_sane.c /Fobuild\temp.win-amd64-cpython-310\Release\_sane.obj
_sane.c
_sane.c(30): fatal error **C1083: Datei (Include) kann nicht geöffnet werden: "sane/sane.h": No such file or directory**
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

- Windows 11 pro
- Intel x64 (why amd64 above?)
- Python 3.10.11
- Windows Build Tools 17.5.4

**Comment by eliasheuninck** [comment]
Installing the libsane-dev package includes the /sane/sane.h file.
$ sudo apt install libsane-dev
I was able to run python-sane after this.

Got the info from hugovk here: https://github.com/python-pillow/Sane/issues/10

**Comment by LuisAlejandro** [comment]
> Installing the libsane-dev package includes the /sane/sane.h file. $ sudo apt install libsane-dev I was able to run python-sane after this.
> 
> Got the info from hugovk here: #10

that would work for debian, but OP asked about Windows

**Comment by eliasheuninck** [comment]
That's correct. I missed that.
