### ISSUE TITLE
header file not found 

### ISSUE THREAD

**Issue by Haroonhsa007** [python-pillow/Sane#90]
_sane.c(30): fatal error C1083: Cannot open include file: 'sane/sane.h': No such file or directory
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by manisandro** [comment]
This is a build environment setup issue, not a python-sane issue.
